# Site settings
title: Alex Villanueva
description: Sitio web personal
author: Alex

# Build settings
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge


permalink: /:title
  
plugins:
  - jekyll-feed
  - jekyll-paginate

# Navigation menu
links:
  - title: Sobre mi
    url: /index.html
  - title: Medicina
    url: /articles/index.html
  - title: Nutrición
    url: /development.html
  - title: Ejercicio Físico
    url: /development.html

# Social-icons
social:
- {icon: 'github',     link: 'https://github.com/alexvillanuevacabrera'}
- {icon: 'linkedin',   link: 'https://www.linkedin.com/in/alex-villanueva-cabrera-064697167/'}
- {icon: 'envelope',   link: 'mailto:nuevavilla9@yahoo.es'}

sharing_button_prompt: 'Feel free to share!'

post_date_prefix: 'Written on'

paginate: 1;
paginate_path: "/articles/page:num/"


baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
